name: 'perfil_municipios'
version: '1.0.0'
config-version: 2

profile: 'perfil_municipios'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  perfil_municipios:
    staging:
      +schema: staging
      +materialized: view
    intermediate:
      +schema: intermediate
      +materialized: ephemeral
    marts:
      +schema: municipios
      +materialized: table
